export const ACTION_ADD_ACCOUNT = "ACTION_ADD_ACCOUNT";
export const MUTATION_ADD_ACCOUNT = "MUTATION_ADD_ACCOUNT";
export const ACTION_REMOVE_ACCOUNT = "ACTION_REMOVE_ACCOUNT";
export const MUTATION_REMOVE_ACCOUNT = "MUTATION_REMOVE_ACCOUNT";
export const STATE_ACCOUNTS = "STATE_ACCOUNTS";
export const ACTION_PUSH_ROUTE ="ACTION_PUSH_ROUTE";
export const MUTATION_PUSH_ROUTE ="MUTATION_PUSH_ROUTE";
export const ACTION_POP_ROUTE = "ACTION_POP_ROUTE";
export const MUTATION_POP_ROUTE ="MUTATION_POP_ROUTE";
export const STATE_ROUTES = "STATE_ROUTES";
export const STATE_SECURITY_MARKETS ="STATE_SECURITY_MARKETS";
export const STATE_SECURITY_SEGMENTS ="STATE_SECURITY_SEGMENTS";
export const STATE_SECURITY_TERRITORIES ="STATE_SECURITY_TERRITORIES";
export const STATE_SECURITY_TYPES = "STATE_SECURITY_TYPES";
export const SECURITY_TYPE_EQUITY = "Equity";
export const SECURITY_TYPE_FIXED_INCOME = "Fixed Income";
export const SECURITY_TYPE_SPECIALITY = "Speciality";
export const STATE_SECURITIES ="STATE_SECURITIES";
export const STATE_SECURITY_CATEGORIES = "STATE_SECURITY_CATEGORIES";
export const GETTER_SECURITIES = "GETTER_SECURITIES";
export const GETTER_SECURITY ="GETTER SECURITY";
export const GETTER_SECURITY_CATEGORIES = "GETTER_SECURITY_CATEGORIES";
export const GETTER_SECURITY_CATEGORY="GETTER_SECURITY_CATEGORY"; 

export const GETTER_SECURITY_MARKET = "GETTER_SECURITY_MARKET";
export const GETTER_SECURITY_MARKETS = "GETTER_SECURITY_MARKETS";
export const GETTER_SECURITY_SEGMENT = "GETTER_SECURITY_SEGMENT";
export const GETTER_SECURITY_SEGMENTS = "GETTER_SECURITY_SEGMENTS";
export const GETTER_SECURITY_TERRITORIES = "GETTER_SECURITY_TERRITORIES";
export const GETTER_SECURITY_TERRITORY= "GETTER_SECURITY_TERRITORY";
export const GETTER_SECURITY_TYPE = "GETTER_SECURITY_TYPE";
export const GETTER_SECURITY_TYPES = "GETTER_SECURITY_TYPES";




