export const ACTION_ADD_ACCOUNT = "ACTION_ADD_ACCOUNT";
export const MUTATION_ADD_ACCOUNT = "MUTATION_ADD_ACCOUNT";
export const ACTION_REMOVE_ACCOUNT = "ACTION_REMOVE_ACCOUNT";
export const MUTATION_REMOVE_ACCOUNT = "MUTATION_REMOVE_ACCOUNT";
export const STATE_ACCOUNTS = "accounts";
export const ACTION_PUSH_ROUTE ="ACTION_PUSH_ROUTE";
export const MUTATION_PUSH_ROUTE ="MUTATION_PUSH_ROUTE";
export const ACTION_POP_ROUTE = "ACTION_POP_ROUTE";
export const MUTATION_POP_ROUTE ="MUTATION_POP_ROUTE";
export const STATE_ROUTES = "routes";

